---
title: "2025"
execute:
  message: false
  warning: false
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(DBI)
library(tictoc)

xaringanExtra::use_panelset()
```

```{r}
#| label: index-table
#| echo: false

challenge_done <- fs::dir_ls("./2025/", recurse = TRUE) |>
  str_subset("query") |>
  str_extract("(?<=query_day)(.*)(?=.sql)") |>
  as.numeric()

not_done <- setdiff(seq(24), challenge_done)

htmltools::tags$style(
  str_c(collapse = "\n",
    c(
      glue::glue(
        "#panelset_001_day-[challenge_done] {color: #409327 !important;}",
        .open = "[", .close = "]"
      ),
      glue::glue(
        "#panelset_001_day-[not_done] {color: #D63131 !important;}",
        .open = "[", .close = "]"
      )
    )
  )
)
```

```{r}
#| label: connect-db
#| echo: false

dotenv::load_dot_env()

con <- DBI::dbConnect(RPostgres::Postgres(),
    host=Sys.getenv("DBHOST"),
    port=as.integer(Sys.getenv("DBPORT")),
    dbname=Sys.getenv("DBNAME"),
)

knitr::opts_chunk$set(connection = "con")
```

:::: {.panelset}

::: {.panel}

# Day 10 {.panel-name}

**Day 10**

```{r, code=readLines("./2025/day_10/query_day10.sql")}
#| label: code-day10
#| eval: false
```

```{r}
#| label: day10
#| echo: false
#| cache: true

tic()
print(dbGetQuery(con, statement = read_file("./2025/day_10/query_day10.sql")))
toc()
```

:::

::: {.panel}

# Day 11 {.panel-name}

**Day 11**

```{bash}
#| label: input-day11
#| echo: false
#| results: false

psql -d advent_of_sql -a -f ./2025/day_11/input_day11.sql
```

```{r, code=readLines("./2025/day_11/query_day11.sql")}
#| label: code-day11
#| eval: false
```

```{r}
#| label: day11
#| echo: false
#| cache: true

tic()
print(dbGetQuery(con, statement = read_file("./2025/day_11/query_day11.sql")))
toc()
```

:::

::: {.panel}

# Day 12 {.panel-name}

**Day 12**

```{bash}
#| label: input-day12
#| echo: false
#| results: false

psql -d advent_of_sql -a -f ./2025/day_12/input_day12.sql
```

```{r, code=readLines("./2025/day_12/query_day12.sql")}
#| label: code-day12
#| eval: false
```

```{r}
#| label: day12
#| echo: false
#| cache: false

entire_query <- read_file("./2025/day_12/query_day12.sql")

n_queries <- str_count(entire_query, ";")

queries <- str_split_fixed(entire_query, ";", n_queries)

tic()
for (i in seq_along(queries)) {
  if (i == n_queries) {
    print(str_glue("\n\n"))
    print(dbGetQuery(con, statement = queries[i]))
  } else {
    command_run <- str_to_upper(word(queries[i], 1))
    n_rows_affected = dbExecute(con, statement = queries[i])
    print(str_glue("{command_run} successfully executed. {n_rows_affected} rows were affected."))
  }
}
toc()
```

:::

::: {.panel}

# Day 13 {.panel-name}

**Day 13**

```{bash}
#| label: input-day13
#| echo: false
#| results: false

psql -d advent_of_sql -a -f ./2025/day_13/input_day13.sql
```

```{r, code=readLines("./2025/day_13/query_day13.sql")}
#| label: code-day13
#| eval: false
```

```{r}
#| label: day13
#| echo: false
#| cache: true

tic()
print(dbGetQuery(con, statement = read_file("./2025/day_13/query_day13.sql")))
toc()
```

:::

::: {.panel}

# Day 14 {.panel-name}

**Day 14**

```{bash}
#| label: input-day14
#| echo: false
#| results: false

psql -d advent_of_sql -a -f ./2025/day_14/input_day14.sql
```

```{r, code=readLines("./2025/day_14/query_day14.sql")}
#| label: code-day14
#| eval: false
```

```{r}
#| label: day14
#| echo: false
#| cache: true

tic()
print(dbGetQuery(con, statement = read_file("./2025/day_14/query_day14.sql")))
toc()
```

:::

::: {.panel}

# Day 15 {.panel-name}

:::

::: {.panel}

# Day 16 {.panel-name}

:::

::: {.panel}

# Day 17 {.panel-name}

:::

::: {.panel}

# Day 18 {.panel-name}

:::

::: {.panel}

# Day 19 {.panel-name}

:::

::: {.panel}

# Day 20 {.panel-name}

:::

::: {.panel}

# Day 21 {.panel-name}

:::

::: {.panel}

# Day 22 {.panel-name}

:::

::: {.panel}

# Day 23 {.panel-name}

:::

::: {.panel}

# Day 24 {.panel-name}

:::

::: {.panel}

# Day 25 {.panel-name}

:::

::::

